name: ${project.name}
description: ${project.description}
version: ${project.version}
authors:
  - MerryChrismas
  - waddlespam
main: de.digitaldevs.playerapi.PlayerAPI
commands:
  coins:
    description: Show your coins